name: SonarCloud Analysis

on:
  push:
    branches:
      - main
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Deshabilita clones superficiales para un mejor análisis de dependencias

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu' # SonarCloud requiere Java para funcionar

      - name: Setup .NET 9.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Install SonarCloud scanner
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Este token lo provee GitHub automáticamente
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}    # Este es el token que debiste guardar en Settings > Secrets
        run: |
          dotnet sonarscanner begin /k:"Joaquinmes18_Calidad_Prueba" /o:"joaquinmes18" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"
          dotnet build ImpulseClub.sln --configuration Release
          dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
